questions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^submit/$', views.submit_quiz, name='submit_quiz'),
]

quiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^questions/', include('questions.urls', namespace="questions")),
    url(r'^admin/', admin.site.urls),
]

questions/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    anwser_text = models.CharField(max_length=200)
    session = models.CharField(max_length=200, default='')

questions/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Answer
import uuid

def index(request):
    question_list = Question.objects.order_by('-pub_date').reverse()
    context = {'question_list': question_list}
    return render(request, 'index.html', context)

def submit_quiz(request):
    anonymouse_user_session = uuid.uuid1()
    print anonymouse_user_session
    for key in request.POST.iterkeys():
        if key.startswith('answer-'):
            question = Question.objects.get(pk=int(key[7:]))
            answer = Answer.objects.create(question=question, anwser_text=request.POST[key], session=anonymouse_user_session)
    return render(request, 'submitted.html')

questions/templates/index.html
{% if question_list %}
    <form action="{% url 'questions:submit_quiz' %}" method="post">
    {% csrf_token %}
        <ul>
        {% for question in question_list %}
            <li>{{ question.question_text }}</li>
            <input type="text" name="answer-{{ question.id }}" />
        {% endfor %}
        </ul>
        <button type="submit">Submit</button>
    </form>
{% else %}
    <p>No questions are available.</p>
{% endif %}

questions/templates/submitted.html
Submitted!